# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'newagentpool'

steps:
- script: |
    pwd
    zip -r src.zip ./src 
    cp src.zip '$(Build.ArtifactStagingDirectory)/.'
    ls -la '$(Build.ArtifactStagingDirectory)/.'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


